name: Attempt to build project

on:
  workflow_dispatch:
#   schedule:
#     - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14', '16', '17' ]
    name: Node v${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          
      - name: Install NPM dependencies
        run: npm install
        
      - name: Build Sample App
        run: npm run build

      - name: Send build metrics to CloudWatch
        run: aws cloudwatch put-metric-data --metric-name BuildSuccess --namespace GitHubSampleApp --value 1 --dimensions NodeVersion=${{ matrix.node }} --region us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
